### PR TITLE
Update agent.js

### PR DESCRIPTION
**Pull request by tanmeshbhokare**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Nice! Let me review the code for a second.

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Um… something’s missing. Are you sure you’ve added the right config var to your Heroku config?

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Some issues need to be fixed before you can merge your PR:
 - I have no idea why, but I've been told that we are not allowed to update "docker-compose.yml". Please make sure to revert your changes before merging your PR.

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Um… something’s missing. Are you sure you’ve added the right config var to your Heroku config?

**Comment by tanmeshbhokare** [comment]
ok

**Review by vanessa-cooper — APPROVED** [review]
Done! The frontend is now connected to the correct backend. Don’t forget to merge the PR.

**Comment by tanmeshbhokare** [comment]
Added config var on heroku settings

**Pull request merged**
